#!/bin/bash

# -d or --device = the iOS device to start.
# -e or --erase = erase devices before run?
# -u or --url = the url to load in Safari on boot

POSITIONAL=()
while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
    -d|--device)
    DEVICE="$2"
    shift # past argument
    shift # past value
    ;;
    -e|--erase)
    ERASE="$2"
    shift
    shift
    ;;
    -u|--url)
    URL="$2"
    shift
    ;;
    *) # unknown option
    POSITIONAL+=("$1") #save it in an array for later
    shift
    ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional paramaters

if [ -z ${DEVICE} ]; then
  echo "No device specified. Expecting a device using either -d or --device"
  exit 1
else
  if [ ${DEVICE} = "ipad-pro" ]; then
    iDEVICE="iPad Pro (12.9-inch) (2nd generation) (11.3)"
  elif [ ${DEVICE} = "ipad" ]; then
    iDEVICE="iPad (5th Generation) (11.2)"
  elif [ ${DEVICE} = "iphone-x" ]; then
    iDEVICE="iPhone X (11.2)"
  elif [ ${DEVICE} = "iphone-se" ]; then
    iDEVICE="iPhone SE (10.3.1)"
  else
    echo "Unknown device. Did you mean one of these: ipad-pro, ipad, iphone-x, iphone-se?"
    exit 1
  fi
fi

if [ ${iDEVICE} ] && [[ -z ${URL} ]]; then
  xcrun instruments -w "${iDEVICE}"
else
  xcrun instruments -w "${iDEVICE}"
  sleep 5;
  xcrun simctl openurl booted https://www.google.com;
fi
